texturePath = "assets/minecraft/textures/item/optifine/enchants/"
items = [
    "aq",
    "ba",
    "bow",
    "bp",
    "cb",
    "ch",
    "chainmail_boots",
    "cv",
    "diamond_boots",
    "diamond_sword",
    "ds",
    "ef",
    "fa",
    "ff",
    "ffchain",
    "ffchaini",
    "ffdiamond",
    "ffdiamondi",
    "ffgold",
    "ffgoldipng",
    "ffgoldi",
    "ffiron",
    "ffironi",
    "ffleather",
    "ffleatheri",
    "ffnether",
    "ffnetheri",
    "fishing_ro",
    "fishing_rod",
    "fl",
    "fp",
    "ft",
    "fw",
    "fwch",
    "fwd",
    "fwg",
    "fwi",
    "fwl",
    "fwn",
    "golden_boots",
    "golden_sword",
    "if",
    "ip",
    "iron_boots",
    "iron_sword",
    "kb",
    "leather_boots_overlay",
    "lo",
    "lr",
    "ls",
    "ly",
    "mg",
    "ms",
    "netherite_boots",
    "netherite_sword",
    "pg",
    "pt",
    "qc",
    "rs",
    "rt",
    "se",
    "sh",
    "sm",
    "stone_sword",
    "th",
    "trident",
    "wooden_sword"
]
for item in items:
    propFile = item + ".properties"
    textureFile = texturePath + item + ".png"
    file = open(propFile,"a")
    line = "\ntexture=" + textureFile
    file.write(line)
    file.close()